project:
  type: website

website:
  title: "BME JuWon's summary note"
  navbar:
    search: true
    logo: ./img/minions2.png
    background: dark
    left:
      - href: index.qmd
        text: Home
        
      - text: "DL summary"
        file: docs/DL/index.qmd
        
      - text: "BME summary"
        file: docs/BME/index.qmd
      
    right:
      - icon: github
        href: https://github.com/jwk1121
        aria-label: JuWon's github
    
  sidebar:
    - style: "floating"
      search: true
      contents:
        - index.qmd
        - docs/DL/index.qmd
        - docs/BME/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

